
version: "3.9"

services:
  database:
    image: postgres:14.1
    ports:
      - "15432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD
    volumes:
      - users_postgresql:/var/lib/postgresql
      - users_postgresql_data:/var/lib/postgresql/data
  frontend:
    build: .
    command: ["/users-server", "-d", "INFO" ]
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOSTNAME=database
    depends_on:
      - database
    ports:
      - "18080:8080"
volumes:
  postgresql:
  postgresql_data:
networks:
  backend:
